Feature/dope 183 create cm connector
ergon/dope-query-builder pull request #3
Opened 2024-03-14 16:04 UTC by jansigi

2024-03-14 17:53 UTC, pgruntz requested changes

2024-03-14 17:53 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/QueryStringBuilder.kt
> +    if (path.isBlank()) {
do you have a test for that case?

2024-03-15 09:07 UTC, sigristjan commented on crystal-map-connector/src/main/kotlin/ch/ergon/dope/CrystalMapAdapter.kt
> +fun <T : Schema> CMObjectList<T>.asSchemaArray() = DopeSchemaArray(element, formatPathToQueryString(name, path))
Created Ticket and added Todo

2024-03-15 09:30 UTC, pgruntz approved these changes

2024-03-15 09:32 UTC, merged