DOPE-232: added all WindowFunctions
ergon/dope-query-builder pull request #50
Opened 2024-08-20 11:07 UTC by jansigi

https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/windowfun.html

2024-08-20 11:08 UTC, jansigi commented
I will add the specific tests after the syntax was reviewed

2024-08-21 11:08 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/WindowFunction.kt
> +                (thirdArgDopeQuery?.let { (if (firstArgDopeQuery != null || secondArgDopeQuery != null) ", " else "") + it.queryString } ?: ""),
i changed it to the nested let, but I think the bracket makes more sense in the window function, and we wouldn't have to use them here four times

2024-08-21 11:14 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/WindowFunction.kt
> +                overClauseDopeQuery.queryString.let { " $it" },
I just noticed now that we can use the`.orEmpty()` function. I changed it in the whole file.
Do you like it more this way?

2024-08-21 12:50 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/WindowFunction.kt
> +    private val nullsModifier: NullsModifier?,
done

2024-08-21 13:08 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/WindowFunction.kt
> +    private val windowReference: String?
done

2024-08-21 13:14 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/WindowFunction.kt
> +            queryString = (windowReferenceDopeQuery?.queryString?.let { " $it" } ?: "") +
I implemented it with a `biuldString`

2024-08-21 13:29 UTC, jansigi commented on core/src/test/kotlin/ch/ergon/dope/buildTest/WindowFunction.kt
> +class WindowFunction {
done

2024-09-18 09:32 UTC, martinagallati-ergon approved these changes
Looks good to me, don't forget to add tests though 🙂

2025-03-07 14:16 UTC, martinagallati requested changes
update diagram

2025-03-07 14:16 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
> +data class WindowFunctionArguments(
why data class?

2025-03-07 14:16 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
> +                if (secondArgDopeQuery != null) {
so if the first arg is null but the second arg is not, it still appends a comma?

2025-03-07 14:16 UTC, martinagallati commented on core/src/test/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/LagTest.kt
> +}
please test both extension functions not just the window ref one
applies to the other window function tests as well

2025-03-07 14:16 UTC, martinagallati commented on core/src/test/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/NthValueTest.kt
> +        val fromModifier = FromModifier.LAST
why didn't you add an import for these? 😄

2025-03-07 14:16 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
please add consts for all string keywords

2025-03-07 15:08 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
> +                if (secondArgDopeQuery != null) {
With the `isNotEmpty()` we check if the first arg was added and if it is, only than we add a comma

2025-03-08 10:55 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
> +sealed class WindowFunction<T : ValidType>(
no, renamed it

2025-03-08 10:56 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/SelectWindowClause.kt
> +class SelectWindowClause<T : ValidType>(
I renamed it to `WindowClause`

2025-03-08 10:57 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/SelectWindowClause.kt
> +                "WINDOW",
Why? It is only used once

2025-03-08 11:03 UTC, jansigi commented on core/src/test/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/LagTest.kt
> +}
done

2025-03-08 11:04 UTC, jansigi commented on core/src/test/kotlin/ch/ergon/dope/resolvable/expression/windowfunction/NthValueTest.kt
> +        val fromModifier = FromModifier.LAST
imported them

2025-03-08 11:05 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
I added a const for the keywords that were used multiple times, when they are only used once i don't think it really matters

2025-03-08 11:09 UTC, jansigi commented on core/src/test/kotlin/ch/ergon/dope/buildTest/WindowFunctionTest.kt
> +}
done

2025-03-08 11:09 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
> +data class WindowFunctionArguments(
made to normal class

2025-03-14 12:10 UTC, martinagallati approved these changes

2025-03-14 12:10 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunction.kt
ah, pg once told me to extract all of them, regardless of how many occurrences there are, but ill ask him next week about that

2025-03-14 12:10 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunctionExpression.kt
> +) : RowScopeExpression<T> {
i like that you split the file up, makes it way more comprehensible 😄 
can you add everything to the diagram, functions included?

2025-03-14 14:25 UTC, jansigi commented on core/src/integrationTest/kotlin/ch/ergon/dope/functions/WindowFunctionsIntegrationTest.kt
> +            .also { println(it.queryString) }
I forgot to remove it

2025-03-14 14:26 UTC, jansigi commented on core/src/test/kotlin/ch/ergon/dope/buildTest/WindowFunctionExpressionTest.kt
> +class WindowFunctionExpressionTest {
renamed it back to `WindowFunctionTest`

2025-03-14 14:27 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/aggregate/AverageExpression.kt
> +    quantifier: AggregateQuantifier? = null,
done

2025-03-14 14:30 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/aggregate/AggregateFunctionExpression.kt
> +    private val resolvable: Resolvable,
yes, great catch

2025-03-14 14:31 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunctionExpression.kt
> +) : RowScopeExpression<T> {
Yes i will add everything

2025-03-19 15:03 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/WindowClause.kt
> +            queryString = "`$reference` AS $windowDefinitionQueryString",
`AS ()` is valid syntax? What should that mean?

2025-03-19 15:05 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/AliasedRowScopeExpression.kt
> +package ch.ergon.dope.resolvable.expression.rowscope
What is the meaning of _rowscope_?

2025-03-19 15:06 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/WindowClause.kt
> +                "WINDOW",
use named parameter with primitive values

2025-03-19 15:07 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +interface RowScopeExpression<T : ValidType> : Expression<T>
don't forget to add all this in the diagram

2025-03-19 15:07 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +interface RowScopeExpression<T : ValidType> : Expression<T>
Why do we need it?

2025-03-19 15:11 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/aggregate/AggregateFunctionExpression.kt
> +    fun withWindow(
why not 'overWindow'?

2025-03-19 15:12 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OverClause.kt
> +sealed interface OverClause : Resolvable
Is it a clause when it is not inheriting 'Clause'?

2025-03-19 15:13 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OverClause.kt
> +            queryString = "$OVER `$windowReference`",
If used more than once, extract constant values to a constant

2025-03-19 15:29 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunctionExpression.kt
> +            queryString = functionName +
I think would build the string like this: 
`"$functionName (${windowFunctionArgumentsDopeQuery?.queryString.orEmpty()}) ${fromModifier?.queryString.orEmpty()} ..."`
To get rid of the spaces beforehand and so

2025-03-19 15:40 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OrderingTerm.kt
> +package ch.ergon.dope.resolvable.expression.rowscope.windowfunction.model
_model_ is a bit too generic

2025-03-19 15:42 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/WindowDefinition.kt
> +            queryString = buildString {
Can we write the string without this string-builder?

2025-03-19 15:46 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/WindowFrameExtent.kt
> +interface FrameAndBetween : Resolvable
What is the difference between FrameBetween and FrameAndBetween? And why no Window-prefix?

2025-03-21 13:42 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/AliasedRowScopeExpression.kt
> +package ch.ergon.dope.resolvable.expression.rowscope
Rowscope means that the query gets executed over a frame (scope) with multiple documents (rows), so basecally it looks at different documents in one query.
I hope thats understandable.

2025-03-21 13:42 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +interface RowScopeExpression<T : ValidType> : Expression<T>
Already is ;)

2025-03-21 13:44 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +interface RowScopeExpression<T : ValidType> : Expression<T>
For the AliasedRowScopeExpression

2025-03-21 13:44 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OverClause.kt
> +            queryString = "$OVER `$windowReference`",
Yes, I tried to do that

2025-03-21 13:47 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/WindowFrameExtent.kt
> +interface FrameAndBetween : Resolvable
So the between needs two arguments `BETWEEN <firstArg> AND <secondArg>` and so i called the first one `FrameBetween` because it comes after the Between and the second one `FrameAndBetween` because it comes after the and. I didn't really find better names so i am very open for suggestion if you have some

2025-03-26 08:30 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/ISelectClause.kt
> +    fun windowReference(reference: String, windowDefinition: WindowDefinition? = null) =
done

2025-03-26 08:30 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/ISelectClause.kt
> +    fun windowReference(windowDeclaration: WindowDeclaration, vararg windowDeclarations: WindowDeclaration) =
done

2025-03-26 08:30 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/WindowClause.kt
> +        val windowDefinitionQueryString = windowDefinitionDopeQuery?.let { "(${it.queryString})" } ?: "()"
yes, changed it

2025-03-26 08:46 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/WindowClause.kt
> +            queryString = "`$reference` AS $windowDefinitionQueryString",
Yes this is valid syntax. It is typically used when the window function is meant to apply to all rows together without segmentation.

2025-03-26 08:47 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/WindowClause.kt
> +                "WINDOW",
done

2025-03-26 08:58 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/WindowFunctionExpression.kt
> +            queryString = functionName +
Hmm, I think it is fine the way it is. If I change it like you sugested, it might end up with multiple spaces in the query string, and I am not really a fan of that.

2025-03-26 09:08 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/WindowDefinition.kt
> +            queryString = buildString {
We could, but i think it would be way more complicated and not very understanding.

2025-03-27 16:24 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OrderingTerm.kt
> +package ch.ergon.dope.resolvable.expression.rowscope.windowfunction.model
renamed to `windowdefinition`

2025-03-27 16:25 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/aggregate/AggregateFunctionExpression.kt
> +    fun withWindow(
removed it, because you use it dirrectly in the function call

2025-03-27 16:25 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowfunction/model/OverClause.kt
> +sealed interface OverClause : Resolvable
renamed

2025-04-02 17:16 UTC, pgruntz approved these changes
Please double-check the diagram as well. (E.g. it's called AggregateFunctionExpression and has a generic)

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +    val functionArguments: List<Selectable?>?
arguments are of type _Selectable?_ - we allow arguments, which are null?

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +    val functionArguments: List<Selectable?>?
Since you are filtering it out anyway, change the type to non-nullable and filter it out earlier

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +        val overClauseDopeQuery = overDefinition?.toDopeQuery(manager)
This is a smell. A clause is a definition?
I would change the type of _OverDefinition_ to _OverWindowClause_

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowdefinition/WindowDefinition.kt
> +    private val windowReference: TypeExpression<StringType>? = null,
A reference is just a string on another place. Would rename to _windowExpression_ or _windowReferenceExpression_

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowdefinition/WindowDefinition.kt
> +        val partitionClauseQueryString = partitionClauseDopeQueries?.joinToString(separator = ", ", prefix = "PARTITION BY ") { it.queryString }
dont we have a function in the QueryStringBuilde as well? Like formatToQueryStringWithSeparator?

2025-04-02 17:16 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowdefinition/WindowFrame.kt
> +                windowFrameExclusion?.let { " ${it.queryString}" }.orEmpty()
Again, make it a bit cleaner, with _joinToString_ or using the _QueryStringBuilder_. Having a space in the beginning or at the end of a string can be overseen quite fast

2025-04-03 15:35 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +        val functionArgumentsQueryString = functionArgumentsDopeQuery.orEmpty().joinToString(
done

2025-04-03 15:40 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +    val functionArguments: List<Selectable?>?
It is selectable because of the `Asterisk` that the `CountAsterisk` uses.
Made it non-nullable

2025-04-03 15:40 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +        val overClauseDopeQuery = overDefinition?.toDopeQuery(manager)
I renamed the variable to overDefinitionDopeQuery

2025-04-03 15:43 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowdefinition/WindowDefinition.kt
> +    private val windowReference: TypeExpression<StringType>? = null,
done

2025-04-03 15:44 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/windowdefinition/WindowFrame.kt
> +                windowFrameExclusion?.let { " ${it.queryString}" }.orEmpty()
done

2025-04-03 15:55 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/rowscope/RowScopeExpression.kt
> +                overClauseDopeQuery?.let { " ${it.queryString}" }.orEmpty(),
done

2025-04-04 06:52 UTC, merged