DOPE-271: added missing returning clause functionality
ergon/dope-query-builder pull request #73
Opened 2024-12-23 17:55 UTC by martinagallati-ergon

2025-01-06 13:17 UTC, pgruntz requested changes

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +    private val returningType: ReturningType = RAW,
Why did you define this default value?

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +                "RETURNING " + returningType.queryString,
Please extract the RETURNING to a constant

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
>                  "RETURNING",
please add named parameter here

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +    returningType: ReturningType = RAW,
again, why these default values?

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +class DeleteReturningSingleClause(
Please extend the diagram as well

2025-01-06 13:17 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/IDeleteClause.kt
> +    fun returning(returningExpression: Returnable, vararg additionalReturningExpressions: Returnable) =
Is this function used anywhere? Do we need it?

2025-01-06 13:17 UTC, pgruntz commented on core/src/test/kotlin/ch/ergon/dope/resolvable/clause/ReturningClauseTest.kt
> +            queryString = "DELETE FROM `someBucket` RETURNING *",
According to the documentation the following is allowed as well:
- `RETURNING bucket.*`
- `RETURNING 1+1`
- `RETURNING field AS f`
- `RETURNING META().id`
- `RETURNING trim(field)`

Do we support all of these cases? Can you add tests if yes

2025-01-07 14:16 UTC, jansigi requested changes

2025-01-07 14:16 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/IDeleteClause.kt
> +    fun returning(typeExpression: TypeExpression<out ValidType>) =
If `TypeExpression` would be `Returnable` we could remove this function

2025-01-07 14:16 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +class ReturningExpression(private val typeExpression: TypeExpression<out ValidType>) : Returnable {
If `TypeExpression` would be `Returnable` we could remove this.

2025-01-20 18:27 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/fromable/Fromable.kt
> +interface Returnable : Resolvable
done

2025-01-20 18:27 UTC, martinagallati-ergon commented on core/src/test/kotlin/ch/ergon/dope/buildTest/DeleteTest.kt
> +            .returning(someStringField()).thenReturning(someNumberField())
I changed it back to a single function

2025-01-20 18:28 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +class ReturningExpression(private val typeExpression: TypeExpression<out ValidType>) : Returnable {
true, like discussed i changed it

2025-01-20 18:28 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +    private val returningType: ReturningType = RAW,
removed the default

2025-01-20 18:28 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +                "RETURNING " + returningType.queryString,
done

2025-01-20 18:28 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
>                  "RETURNING",
done

2025-01-20 18:28 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +class DeleteReturningSingleClause(
done

2025-01-20 18:29 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/IDeleteClause.kt
> +    fun returning(returningExpression: Returnable, vararg additionalReturningExpressions: Returnable) =
there shouldn't be any unused functions anymore

2025-01-20 18:29 UTC, martinagallati-ergon commented on core/src/test/kotlin/ch/ergon/dope/resolvable/clause/ReturningClauseTest.kt
> +            queryString = "DELETE FROM `someBucket` RETURNING *",
i added different tests for the different use cases, tell me if you want more / you feel like something is missing

2025-01-20 18:30 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/IDeleteClause.kt
> +    fun returning(typeExpression: TypeExpression<out ValidType>) =
i changed the typeexpression to be a returnable, now theres only one function again

2025-01-20 18:30 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/IUpdateClause.kt
> +    fun returning(typeExpression: TypeExpression<out ValidType>) =
as above

2025-01-20 18:30 UTC, martinagallati-ergon commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +class ReturningExpression(private val typeExpression: TypeExpression<out ValidType>) : Returnable {
as above

2025-01-29 09:00 UTC, jansigi approved these changes

2025-02-11 14:04 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AverageExpression.kt
> +    number: Field<NumberType>,
Would keep the Type Variable T

2025-02-11 14:07 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/MeanExpression.kt
> +    number: Field<NumberType>,
dito

2025-02-11 14:07 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/MedianExpression.kt
> +    number: Field<NumberType>,
dito

2025-02-11 14:07 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/StandardDeviationExpression.kt
> +    number: Field<NumberType>,
dito

2025-02-11 14:07 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/SumExpression.kt
> +    number: Field<NumberType>,
dito

2025-02-11 14:08 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/VarianceExpression.kt
> +    number: Field<NumberType>,
dito

2025-02-11 14:31 UTC, jansigi commented on core/src/main/kotlin/ch/ergon/dope/resolvable/fromable/Fromable.kt
>  package ch.ergon.dope.resolvable.fromable
The more i see this packe and especially now that we update the interface structure i think we should **rename** the package as well as this class.
My suggestion for the package would be `querysource` or `sourceable`.
For the File i would go for `QueryRoles` or `QueryParticipants`.
These are only suggestions, but I think its necessary to rename them now.

2025-02-11 19:18 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AverageExpression.kt
> +    number: Field<NumberType>,
If the generic is not used, we should remove it

2025-02-11 19:49 UTC, pgruntz approved these changes

2025-02-11 19:49 UTC, pgruntz commented on core/src/test/kotlin/ch/ergon/dope/buildTest/ObjectTest.kt
> -        val subQuery = create.selectDistinct(someStringField(), someNumberField()).from(someBucket("other")).alias("subQuery")
why did you change this test?

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/AliasedTypeExpression.kt
> +fun Number.alias(string: String): AliasedTypeExpression<NumberType> = toDopeType().alias(string)
please rename parameters to _alias_

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/fromable/Fromable.kt
>  package ch.ergon.dope.resolvable.fromable
Agree, the package-structure should ressemble our diagram. I think we should discuss it offline

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +        val returnablesDopeQuery = returnables.map {
returnableDopeQuer**ies** (it's a list)

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AggregateExpression.kt
> +    private val field: Field<out ValidType>,
nice

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AggregateExpression.kt
> +                "$symbol($quantifier ${fieldDopeQuery.queryString})"
the enum AggregateQuantifier should have a string-representation (like ReturningType)

2025-02-11 19:49 UTC, pgruntz commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AliasedAggregateExpression.kt
> +                "AS",
please add named parameters when passing plain values

2025-02-14 13:57 UTC, jansigi approved these changes

2025-02-14 14:00 UTC, martinagallati commented on core/src/test/kotlin/ch/ergon/dope/buildTest/ObjectTest.kt
> -        val subQuery = create.selectDistinct(someStringField(), someNumberField()).from(someBucket("other")).alias("subQuery")
Range predicates like `ANY` cannot iterate over objects.

2025-02-14 14:00 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/AliasedTypeExpression.kt
> +fun Number.alias(string: String): AliasedTypeExpression<NumberType> = toDopeType().alias(string)
done

2025-02-14 14:00 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/clause/model/ReturningClause.kt
> +        val returnablesDopeQuery = returnables.map {
done

2025-02-14 14:01 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AggregateExpression.kt
> +    private val field: Field<out ValidType>,
thanks, my finest work yet

2025-02-14 14:01 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AggregateExpression.kt
> +                "$symbol($quantifier ${fieldDopeQuery.queryString})"
done

2025-02-14 14:01 UTC, martinagallati commented on core/src/main/kotlin/ch/ergon/dope/resolvable/expression/unaliased/aggregator/AliasedAggregateExpression.kt
> +                "AS",
done

2025-02-14 17:10 UTC, merged